FROM ubuntu:14.04
MAINTAINER Vyacheslav Krachkov <vskrachkov@gmail.com>
RUN apt-get update -y
RUN apt-get install -y python3 python3-pip
RUN apt-get install -y libcurl4-openssl-dev
RUN apt-get install libxml2-dev libxslt-dev
RUN apt-get install python-dev python3-dev build-essential libssl-dev libffi-dev libxml2-dev libxslt1-dev zlib1g-dev python-pip
COPY 
